/*
 * Here comes the text of your license
 * Each line should be prefixed with  * 
 */
package dbms;

import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author anonymous
 */
public class Register extends javax.swing.JFrame {

    Connection con;
    ResultSet rs;
    PreparedStatement pst;

    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        lasttxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        middletxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        regbtn = new javax.swing.JButton();
        firsttxt = new javax.swing.JTextField();
        updatebtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        yearbox = new javax.swing.JComboBox();
        genderbox = new javax.swing.JComboBox();
        regbtn2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        coursebox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        studentidtxt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        searchtxt = new javax.swing.JTextField();
        printbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Student Form");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        status.setText("Fill up form below");

        lasttxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lasttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lasttxtActionPerformed(evt);
            }
        });
        lasttxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lasttxtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lasttxtKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Last name :");

        middletxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        middletxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middletxtActionPerformed(evt);
            }
        });
        middletxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                middletxtKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Middle Initial :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("First name :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Gender :");

        regbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1467696584_list-add-user.png"))); // NOI18N
        regbtn.setText("Register");
        regbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtnActionPerformed(evt);
            }
        });

        firsttxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firsttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firsttxtActionPerformed(evt);
            }
        });
        firsttxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                firsttxtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firsttxtKeyTyped(evt);
            }
        });

        updatebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update.png"))); // NOI18N
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Year :");

        yearbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yearbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        yearbox.setToolTipText("");

        genderbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        genderbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));
        genderbox.setToolTipText("");

        regbtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1475560505_Cancel.png"))); // NOI18N
        regbtn2.setText("Clear");
        regbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtn2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Course :");

        coursebox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        coursebox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        coursebox.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Student ID :");

        studentidtxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentidtxtActionPerformed(evt);
            }
        });
        studentidtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                studentidtxtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                studentidtxtKeyTyped(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel2.png"))); // NOI18N
        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel4))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firsttxt)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lasttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(middletxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 1, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(updatebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(33, 33, 33))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(status, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(genderbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(yearbox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(coursebox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(regbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGap(67, 67, 67)
                                    .addComponent(regbtn))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lasttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(middletxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firsttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(genderbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(coursebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(yearbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regbtn)
                    .addComponent(updatebtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regbtn2)
                    .addComponent(jButton2))
                .addGap(21, 21, 21))
        );

        list_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        list_table.getTableHeader().setReorderingAllowed(false);
        list_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list_table);

        jLabel2.setText("Search :");

        searchtxt.setToolTipText("Search by lastname,idnumber or firstname");
        searchtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchtxtKeyTyped(evt);
            }
        });

        printbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1467696633_BT_print.png"))); // NOI18N
        printbtn.setText("Print");
        printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbtnActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1475861187_view-refresh.png"))); // NOI18N
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Close.png"))); // NOI18N
        jButton3.setText("Delete All");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(printbtn)
                        .addGap(24, 24, 24))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 91, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printbtn)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        con = (com.mysql.jdbc.Connection) connection.ConnectDb();
        Year();
        List();
        Course();
    }//GEN-LAST:event_formWindowOpened

    private void lasttxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lasttxtKeyPressed

    }//GEN-LAST:event_lasttxtKeyPressed

    private void lasttxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lasttxtKeyTyped

    }//GEN-LAST:event_lasttxtKeyTyped

    private void regbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtnActionPerformed
String a,b,c,d,e,f,g;
a=lasttxt.getText();
b= middletxt.getText();
c=firsttxt.getText();
d=(String) genderbox.getSelectedItem();
e=studentidtxt.getText();
f=(String) coursebox.getSelectedItem();
g=(String) yearbox.getSelectedItem();
if(a.isEmpty()||b.isEmpty()||c.isEmpty()||e.isEmpty()||f.equals("Course")||g.equals("Year")){
        JOptionPane.showMessageDialog(rootPane, "No field should be empty!");
}else{        
        try{String validation = "Select * from list where id='"+e+"' or lname='"+a+"' and mi='"+b+"' and fname = '"+c+"' and gender = '"+d+"' and course = '"+f+"' and year = '"+g+"'";
                pst=con.prepareStatement(validation);
                rs=pst.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(rootPane, "Student is already on the list!");
                }else if(f.equals("Year")){
                    JOptionPane.showMessageDialog(rootPane, "Please select Year level!");
                }else{
                    try{String insert="insert into list(lname,mi,fname,gender,id,course,year)values('"+a+"','"+b+"','"+c+"','"+d+"','"+e+"','"+f+"','"+g+"')";
                            pst=con.prepareStatement(insert);
                            pst.execute();
                                    lasttxt.setText("");
                                    middletxt.setText("");
                                    firsttxt.setText("");
                                    genderbox.setSelectedItem("M");
                                    studentidtxt.setText("");
                                    yearbox.setSelectedItem("Year");
                                    JOptionPane.showMessageDialog(rootPane, "Data Saved!");
                                    List();
                    }catch(Exception ex){}

                }

        }catch(Exception ex){JOptionPane.showMessageDialog(rootPane, ex);}        
}

    }//GEN-LAST:event_regbtnActionPerformed

    private void middletxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middletxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middletxtActionPerformed

    private void searchtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtxtKeyTyped

        String sql = "select concat(id,'')as '"+"Student ID"+"',concat(lname,', ',fname, ' ',mi,'.') as Name,gender,concat(course, ' - ', year) as '"+"Course & Year"+"' from list where lname LIKE ? or fname LIKE ? or year LIKE ? or id LIKE ?";
        try {
            pst = (com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql);
            pst.setString(1, searchtxt.getText() + "%");
            pst.setString(2, searchtxt.getText() + "%");
            pst.setString(3, searchtxt.getText() + "%");
            pst.setString(4, searchtxt.getText() + "%");
            rs = pst.executeQuery();
            list_table.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }


    }//GEN-LAST:event_searchtxtKeyTyped

    private void firsttxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firsttxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_firsttxtKeyPressed

    private void firsttxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firsttxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_firsttxtKeyTyped

    private void firsttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firsttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firsttxtActionPerformed

    private void printbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbtnActionPerformed

        Calendar c = Calendar.getInstance();
        String month1 = c.getDisplayName(Calendar.MONTH, Calendar.LONG, Locale.ENGLISH);
        GregorianCalendar gc = new GregorianCalendar();

        int day1 = gc.get(Calendar.DAY_OF_MONTH);
        int year1 = gc.get(Calendar.YEAR);

        try {
            this.setAlwaysOnTop(false);
            MessageFormat headerFormat = new MessageFormat("Students List ");
            MessageFormat footerFormat = new MessageFormat(month1 + " " + day1 + "," + year1 + "        page {0}");
            list_table.print(JTable.PrintMode.FIT_WIDTH, headerFormat, footerFormat);
            this.setAlwaysOnTop(true);
        } catch (PrinterException pe) {
            JOptionPane.showMessageDialog(rootPane, pe.getMessage());
        }

    }//GEN-LAST:event_printbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
String a,b,c,d,e,f,g;
a=lasttxt.getText();
b= middletxt.getText();
c=firsttxt.getText();
d=(String) genderbox.getSelectedItem();
e=studentidtxt.getText();
f=(String) coursebox.getSelectedItem();
g=(String) yearbox.getSelectedItem();
if(a.isEmpty()||b.isEmpty()||c.isEmpty()||e.isEmpty()||f.equals("Course")||g.equals("Year")){
        JOptionPane.showMessageDialog(rootPane, "No field should be empty!");
}else{        
        try{String validation = "Select * from list where id='"+e+"' or lname='"+a+"' and mi='"+b+"' and fname = '"+c+"'";
                pst=con.prepareStatement(validation);
                rs=pst.executeQuery();
                if(rs.next()){
 
                    try{String update="update list set lname = '"+a+"',mi = '"+b+"',fname = '"+c+"',gender = '"+d+"',id = '"+e+"',course = '"+f+"', year = '"+g+"'";
                            pst=con.prepareStatement(update);
                            pst.execute();
                                    lasttxt.setText("");
                                    middletxt.setText("");
                                    firsttxt.setText("");
                                    genderbox.setSelectedItem("M");
                                    studentidtxt.setText("");
                                    yearbox.setSelectedItem("Year");
                                    JOptionPane.showMessageDialog(rootPane, "Data updated!");
                                    List();
                    }catch(Exception ex){}
                }else if(f.equals("Year")){
                    JOptionPane.showMessageDialog(rootPane, "Please select Year level!");
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Student not found!");
                }

        }catch(Exception ex){JOptionPane.showMessageDialog(rootPane, ex);}        
}


    }//GEN-LAST:event_updatebtnActionPerformed

    private void list_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_tableMouseClicked
try{int row=list_table.getSelectedRow();
        String Table_click = (list_table.getModel().getValueAt(row, 0).toString());
        String click = "Select * from list where id = '"+Table_click+"'";
        pst=con.prepareStatement(click);
        rs=pst.executeQuery();
        while(rs.next()){
                String id = rs.getString("id");
                String lname = rs.getString("lname");
                String mi = rs.getString("mi");
                String fname = rs.getString("fname");
                String gender = rs.getString("gender");
                String year = rs.getString("year");
                String course = rs.getString("course");
                
                studentidtxt.setText(id);
                lasttxt.setText(lname);
                middletxt.setText(mi);
                firsttxt.setText(fname);
                genderbox.setSelectedItem(gender);
                yearbox.setSelectedItem(year);
                coursebox.setSelectedItem(course);
                
                
        }
}catch(Exception ex){}


    }//GEN-LAST:event_list_tableMouseClicked

    private void lasttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lasttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lasttxtActionPerformed

    private void middletxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_middletxtKeyTyped
       if(middletxt.getText().length()>=1&&!(evt.getKeyChar()==KeyEvent.VK_DELETE||evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)) {
            getToolkit().beep();
            evt.consume();
         }
        char keyChar = evt.getKeyChar();
        if (Character.isLowerCase(keyChar)) {
          evt.setKeyChar(Character.toUpperCase(keyChar));
        }
    }//GEN-LAST:event_middletxtKeyTyped

    private void regbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtn2ActionPerformed
lasttxt.setText("");
middletxt.setText("");
firsttxt.setText("");
genderbox.setSelectedItem("M");
studentidtxt.setText("");
yearbox.setSelectedItem("Year");
coursebox.setSelectedItem("Course");
    }//GEN-LAST:event_regbtn2ActionPerformed

    private void studentidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentidtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentidtxtActionPerformed

    private void studentidtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentidtxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentidtxtKeyPressed

    private void studentidtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentidtxtKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c))|| (c == KeyEvent.VK_BACK_SPACE)|| (c == KeyEvent.VK_DELETE)){
            evt.consume();
        }
        if(studentidtxt.getText().length()>=9&&!(evt.getKeyChar()==KeyEvent.VK_DELETE||evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_studentidtxtKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
List();
searchtxt.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String a,b,c,d,e,f,g;
a=lasttxt.getText();
b= middletxt.getText();
c=firsttxt.getText();
d=(String) genderbox.getSelectedItem();
e=studentidtxt.getText();
f=(String) coursebox.getSelectedItem();
g=(String) yearbox.getSelectedItem();
if(a.isEmpty()||b.isEmpty()||c.isEmpty()||e.isEmpty()||f.equals("Course")||g.equals("Year")){
        JOptionPane.showMessageDialog(rootPane, "No field should be empty!");
}else{
 int reply = JOptionPane.showConfirmDialog(rootPane, "Remove data from database","Are you sure?", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {    

              try{String del = "delete from list where id = '"+e+"' and lname = '"+a+"'";
                  pst = con.prepareStatement(del);
                  pst.execute();
                  List();
                  lasttxt.setText("");
                  middletxt.setText("");
                  firsttxt.setText("");
                  genderbox.setSelectedItem("M");
                  studentidtxt.setText("");
                  yearbox.setSelectedItem("Year");
                  coursebox.setSelectedItem("Course");
                  JOptionPane.showMessageDialog(rootPane, "Data deleted!");
              }catch(Exception ex){}  
           
    }else{
         JOptionPane.showMessageDialog(rootPane, "Action canceled!");   
        }

}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 int reply = JOptionPane.showConfirmDialog(rootPane, "Doing this action might get the system hanging","Are you sure?", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {  
                try{String del = "truncate list";
                    pst = con.prepareStatement(del);
                    pst.execute();
                    List();
                    JOptionPane.showMessageDialog(rootPane, "All data cleared!");
                }catch(Exception ex){}

        }else{
            JOptionPane.showMessageDialog(rootPane, "Action canceled!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox coursebox;
    private javax.swing.JTextField firsttxt;
    private javax.swing.JComboBox genderbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lasttxt;
    private javax.swing.JTable list_table;
    private javax.swing.JTextField middletxt;
    private javax.swing.JButton printbtn;
    private javax.swing.JButton regbtn;
    private javax.swing.JButton regbtn2;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JLabel status;
    private javax.swing.JTextField studentidtxt;
    private javax.swing.JButton updatebtn;
    private javax.swing.JComboBox yearbox;
    // End of variables declaration//GEN-END:variables
public void List(){
    try{String list = "select concat(id,'')as '"+"Student ID"+"',concat(lname,', ',fname, ' ',mi,'.') as Name,gender,concat(course, ' - ',year) as '"+"Course & Year"+"' from list order by lname ASC";
        pst=con.prepareStatement(list);
        rs=pst.executeQuery();
        list_table.setModel(DbUtils.resultSetToTableModel(rs));
    
    }catch(Exception ex){}
}

public void Year(){
//year drop down
try{    String sql = "Select * from year order by cid ASC";
    pst=con.prepareStatement(sql);
    rs=pst.executeQuery();
Vector nameitem = new Vector();
            while(rs.next()){
                nameitem.add( rs.getString("year"));
                yearbox.setModel(new DefaultComboBoxModel(nameitem));
            }    
}catch(Exception ex){
    JOptionPane.showMessageDialog(rootPane, ex);
}
}

public void Course(){
try{    String sql = "Select * from course order by cid ASC";
    pst=con.prepareStatement(sql);
    rs=pst.executeQuery();
            Vector nameitem = new Vector();
            while(rs.next()){
                nameitem.add( rs.getString("course"));
                coursebox.setModel(new DefaultComboBoxModel(nameitem));
            }    
}catch(Exception ex){
    JOptionPane.showMessageDialog(rootPane, ex);
}    
}

}
